// Common
export const TODOS_AJAX_FAILURE = 'TODOS_AJAX_FAILURE';

// TodoMain
export const TODOS_FETCH_REQUEST = 'TODOS_FETCH_REQUEST';
export const TODOS_FETCH_SUCCESS = 'TODOS_FETCH_SUCCESS';
export const TODOS_ADD_REQUEST = 'TODOS_ADD_REQUEST';
export const TODOS_ADD_SUCCESS = 'TODOS_ADD_SUCCESS';
export const TODOS_REMOVE_REQUEST = 'TODOS_REMOVE_REQUEST';
export const TODOS_REMOVE_SUCCESS = 'TODOS_REMOVE_SUCCESS';
export const TODOS_COMPLETE_REQUEST = 'TODOS_COMPLETE_REQUEST';
export const TODOS_COMPLETE_SUCCESS = 'TODOS_COMPLETE_SUCCESS';
export const TODOS_EDIT_REQUEST = 'TODOS_EDIT_REQUEST';
export const TODOS_EDIT_SUCCESS = 'TODOS_EDIT_SUCCESS';
export const TODOS_REMOVE_COMPLETED_REQUEST = 'TODOS_REMOVE_COMPLETED_REQUEST';
export const TODOS_REMOVE_COMPLETED_SUCCESS = 'TODOS_REMOVE_COMPLETED_SUCCESS';
export const TODOS_NAVIGATE_TO_DETAIL = 'TODOS_NAVIGATE_TO_DETAIL';

// TodoDetail
export const TODOS_BACK_TO_LIST = 'TODOS_BACK_TO_LIST';
export const TODOS_GET_DETAIL_REQUEST = 'TODOS_GET_DETAIL_REQUEST';
export const TODOS_GET_DETAIL_SUCCESS = 'TODOS_GET_DETAIL_SUCCESS';

// Visibility filter
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const SHOW_ALL = 'SHOW_ALL';
export const SHOW_COMPLETED = 'SHOW_COMPLETED';
export const SHOW_ACTIVE = 'SHOW_ACTIVE';
